project_id = "evxmwcluivveyvbksehw"

[functions.validate-admin]
verify_jwt = false

[functions.secure-admin-auth]
verify_jwt = false

[functions.get-admin-data]
verify_jwt = false

[functions.clear-attendees]
verify_jwt = false